//
//  FashionPersonalizationService.swift
//  HPIkeaSampleApp
//
//  Created by Vinit Chapla on 10/12/25.
//

import Foundation
import UIKit
import Photos
//import AIModelOnDeviceSDK

final class FashionPersonalizationService {
    static let shared = FashionPersonalizationService()
    
    private let sdk = AIModelOnDeviceSDK.shared
    private let clusterService = PhotoClusterService.shared
    
    // Track all API requests and responses (from SDK)
    var requestMap = PersonalizationRequestMap()
    
    private let productImageMapKey = "PersonalizedProductImageMap"
    
    private init() {
        
    }
    
    /// Runs the complete personalization pipeline
    func runPersonalizationPipeline(
        progressUpdate: @escaping (String) -> Void
    ) async throws {
        // Always clear cache at the start of personalization
        print("🗑️ Clearing old personalized images from cache...")
        // //LogWriter.shared.write("🗑️ Clearing old personalized images from cache...")
        print("✅ Cache cleared - starting personalization pipeline")
        // //LogWriter.shared.write("✅ Cache cleared - starting personalization pipeline")
        
        progressUpdate("Fetching photos from gallery...")
        
        // Step 1: Fetch photos with location
//        let photos = try await clusterService.fetchPhotos(
//            limit: 1000
//        )
//        
//        guard !photos.isEmpty else {
//            throw PersonalizationError.noPhotosFound
//        }
        
        let (photos, photoClusters) = try await clusterService.fetchPhotosWithLocationCached(
            limit: 1000,
            radius: 500.0,
            forceRefresh: true
        )
        
        guard !photos.isEmpty else {
            throw PersonalizationError.noPhotosFound
        }
        
        progressUpdate("Selecting best photos...")
        
        // Step 2: Select largest cluster
        guard let largestCluster = clusterService.getLargestCluster(from: photoClusters) else {
            throw PersonalizationError.insufficientPhotos
        }
        
        progressUpdate("Selecting best photos...")
        
        // Step 2: Load images from cluster
        var clusterImages: [UIImage] = []
        var clusterIdentifiers: [String] = []
        let batchSize = 10
        
        for batchStart in stride(from: 0, to: largestCluster.photos.count, by: batchSize) {
            let batchEnd = min(batchStart + batchSize, photos.count)
            let batch = Array(photos[batchStart..<batchEnd])
            
            var batchImages: [UIImage] = []
            var batchIdentifiers: [String] = []
            
            for photoLocation in batch {
                if let image = await clusterService.loadImageOfAsset(from: photoLocation.asset) {
                    batchImages.append(image)
                    batchIdentifiers.append(photoLocation.asset.localIdentifier)
                }
            }
            
            autoreleasepool {
                clusterImages.append(contentsOf: batchImages)
                clusterIdentifiers.append(contentsOf: batchIdentifiers)
            }
        }
        
        guard !clusterImages.isEmpty else {
            throw PersonalizationError.failedToLoadImages
        }
        
        progressUpdate("Analyzing images for faces...")
        
        do {
            try await fetchBestFashionPhotoFromRemote(clusterImages: clusterImages) { msg in
                progressUpdate(msg)
            }
        }catch let err {
            throw err
        }
    }
    
    func fetchBestFashionPhotoFromRemote(clusterImages:[UIImage] , progressUpdate: @escaping (String) -> Void) async throws {
        // Step 4: Find best face images using FaceVerificationHandler (similar to PersonalizationService Step 4)
        let faceResults = try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<[FaceObservationData], Error>) in
            FaceVerificationHandler.shared.filterResults(clusterImages, category: nil) { results in
                continuation.resume(returning: results)
            }
        }

        guard !faceResults.isEmpty else {
            throw PersonalizationError.noValidImages
        }

        // Pick the face that appears most frequently, then take the highest-quality image for that face.
        // (This uses 512-D embeddings generated by the SDK.)
        let menFaceResults = faceResults.compactMap { observationData in
            return (observationData.gender == "Men") ? observationData : nil
        }
        if menFaceResults.count > 0 {
            let picked = FaceVerificationHandler.shared.bestImageForMostFrequentFace(from: menFaceResults, similarityThreshold: 0.80)
            guard let bestFace = picked?.best else {
                throw PersonalizationError.noValidFaceFound
            }

            
            progressUpdate("Tagging face images...")
            
            guard let bestImg = picked?.best.image else {
                print("⚠️ Failed to best face image")
                // //LogWriter.shared.write("⚠️ Failed to best face image")
                return
            }
            
            let success = ImageStorageHandler.shared.saveBestUserImage(bestImg, withName: "men_face")
            if success {
                print("✅ Best face image saved successfully")
                // //LogWriter.shared.write("✅ Best face image saved successfully")
                print("   Best face quality score: \(String(format: "%.2f", bestFace.qualityScore))")
                // //LogWriter.shared.write("   Best face quality score: \(String(format: "%.2f", bestFace.qualityScore))")
                if let gender = bestFace.gender {
                    print("   Detected gender: \(gender)")
                    //LogWriter.shared.write("   Detected gender: \(gender)")
                }
            } else {
                print("⚠️ Failed to save best face image")
                //LogWriter.shared.write("⚠️ Failed to save best face image")
            }
        }
        let womenFaceResults = faceResults.compactMap { observationData in
            return (observationData.gender == "Women") ? observationData : nil
        }
        if womenFaceResults.count > 0 {
            let picked = FaceVerificationHandler.shared.bestImageForMostFrequentFace(from: womenFaceResults, similarityThreshold: 0.80)
            guard let bestFace = picked?.best else {
                throw PersonalizationError.noValidFaceFound
            }

            
            progressUpdate("Tagging face images...")
            
            guard let bestImg = picked?.best.image else {
                print("⚠️ Failed to best face image")
                //LogWriter.shared.write("⚠️ Failed to best face image")
                return
            }
            
            let success = ImageStorageHandler.shared.saveBestUserImage(bestImg, withName: "women_face")
            if success {
                print("✅ Best face image saved successfully")
                //LogWriter.shared.write("✅ Best face image saved successfully")
                print("   Best face quality score: \(String(format: "%.2f", bestFace.qualityScore))")
                //LogWriter.shared.write("   Best face quality score: \(String(format: "%.2f", bestFace.qualityScore))")
                if let gender = bestFace.gender {
                    print("   Detected gender: \(gender)")
                    //LogWriter.shared.write("   Detected gender: \(gender)")
                }
            } else {
                print("⚠️ Failed to save best face image")
                //LogWriter.shared.write("⚠️ Failed to save best face image")
            }
        }
        progressUpdate("Face personalization completed!")
    }
}

